/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * AlterarSenha.java
 *
 * Created on 06/12/2011, 17:33:07
 */

package Interfaces;

import conexaoBancoDeDados.conexaoMySql;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Aluno T
 */
public class AlterarSenha extends javax.swing.JDialog {

    /** Creates new form AlterarSenha */
    public AlterarSenha(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        bd_default();
        ComboBox();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tf_SenhaNova = new javax.swing.JTextField();
        bt_gravar = new javax.swing.JButton();
        cb_NomeUsuarioAtual = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        tf_SenhaAntiga = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Conta de Usuário");
        setAlwaysOnTop(true);
        setResizable(false);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Alterar Senha", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("SansSerif", 0, 12), new java.awt.Color(0, 0, 255))); // NOI18N

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setText("Nome de Usuário:");

        jLabel2.setText("Nova Senha:");

        tf_SenhaNova.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_SenhaNovaActionPerformed(evt);
            }
        });

        bt_gravar.setText("Gravar");
        bt_gravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_gravarActionPerformed(evt);
            }
        });

        cb_NomeUsuarioAtual.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-" }));

        jLabel3.setText("Senha Antiga:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bt_gravar)
                    .addComponent(cb_NomeUsuarioAtual, 0, 167, Short.MAX_VALUE)
                    .addComponent(jLabel3)
                    .addComponent(tf_SenhaAntiga)
                    .addComponent(jLabel2)
                    .addComponent(tf_SenhaNova))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cb_NomeUsuarioAtual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tf_SenhaAntiga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tf_SenhaNova, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addComponent(bt_gravar)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        java.awt.Dimension dialogSize = getSize();
        setLocation((screenSize.width-dialogSize.width)/2,(screenSize.height-dialogSize.height)/2);
    }// </editor-fold>//GEN-END:initComponents

    private void tf_SenhaNovaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_SenhaNovaActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_tf_SenhaNovaActionPerformed
    conexaoMySql valida = new conexaoMySql();
    private void bt_gravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_gravarActionPerformed
        // TODO add your handling code here:
        valida.executaComandosSql("SELECT * FROM login WHERE log_usuario = '"+cb_NomeUsuarioAtual.getSelectedItem()+"'");
        try {
            if (cb_NomeUsuarioAtual.getSelectedItem().equals("-") || tf_SenhaNova.getText().equals("") || tf_SenhaAntiga.getText().equals("")) {

                throw new IllegalAccessError();
            }else{
            //String retorna = valida.resultset.getString("log_senha");
                while (valida.resultset.next()) {
                    if(valida.resultset.getString("log_senha").equals(tf_SenhaAntiga.getText())){
                        try{

                    valida.executaComandosSql("select * from login");
                    valida.resultset.first();
                    //JOptionPane.showMessageDialog(this,"asdf");
                    valida.statement.executeUpdate("UPDATE login SET log_senha = '"+tf_SenhaNova.getText()+"' "
                            + "WHERE log_usuario = '"+cb_NomeUsuarioAtual.getSelectedItem()+"' AND log_senha = '"+tf_SenhaAntiga.getText()+"'");

                    JOptionPane.showMessageDialog(this,"Senha de usuário alterado com sucesso","Conta de Usuário",JOptionPane.INFORMATION_MESSAGE);
                    LimpaComboBox();
                }catch(Exception ex){
                    JOptionPane.showMessageDialog(this,"Erro de sintaxe");
                }
                        break;
                    }else{
                        JOptionPane.showMessageDialog(this,"Senha antiga incorreta","Cadastro de Usuário",JOptionPane.WARNING_MESSAGE);
                        
                    }
                }
            
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Usuário ou senha estão incorretos", "Erro de Autenticação", JOptionPane.ERROR_MESSAGE);
            
        } catch (IllegalAccessError erroDado){
            JOptionPane.showMessageDialog(this,"Preencha Todos os Campos!", "", 2);
            tf_SenhaNova.requestFocus();
        }


/*
        try {

            if (cb_NomeUsuarioAtual.getSelectedItem().equals("-") || tf_SenhaNova.getText().equals("") || tf_SenhaAntiga.getText().equals("")) {

                throw new IllegalAccessError();

            } else {

                try{

                    valida.executaComandosSql("select * from login");
                    valida.resultset.first();
                    //JOptionPane.showMessageDialog(this,"asdf");
                    valida.statement.executeUpdate("UPDATE login SET log_senha = '"+tf_SenhaNova.getText()+"' "
                            + "WHERE log_usuario = '"+cb_NomeUsuarioAtual.getSelectedItem()+"' AND log_senha = '"+tf_SenhaAntiga.getText()+"'");

                    JOptionPane.showMessageDialog(this,"Senha de usuário alterado com sucesso","Conta de Usuário",JOptionPane.INFORMATION_MESSAGE);
                    LimpaComboBox();
                }catch(Exception ex){
                    JOptionPane.showMessageDialog(this,"Erro de sintaxe");
                }

            }

        } catch (IllegalAccessError erroDado) {

            JOptionPane.showMessageDialog(this,"Preencha Todos os Campos!", "", 2);
            tf_SenhaNova.requestFocus();
        }*/


        
}//GEN-LAST:event_bt_gravarActionPerformed


    public void LimpaComboBox(){

        tf_SenhaAntiga.setText("");
        tf_SenhaNova.setText("");
        cb_NomeUsuarioAtual.removeAllItems();
        cb_NomeUsuarioAtual.addItem("-");
        ComboBox();
    }

    public void ComboBox(){

       valida.executaComandosSql("SELECT log_usuario FROM login ORDER BY log_usuario");
        try {
            while (valida.resultset.next()) {

                if(valida.resultset.getString("log_usuario").equals(null)){

                }else{
                cb_NomeUsuarioAtual.addItem(valida.resultset.getString("log_usuario"));
                }

            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Usuário ou senha estão incorretos", "Erro de Autenticação", JOptionPane.ERROR_MESSAGE);
        }
    }

    public void bd_default() {
        valida.eventuaCenexao();


    }

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AlterarSenha dialog = new AlterarSenha(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_gravar;
    private javax.swing.JComboBox cb_NomeUsuarioAtual;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField tf_SenhaAntiga;
    private javax.swing.JTextField tf_SenhaNova;
    // End of variables declaration//GEN-END:variables

}
