

package Interfaces;

import conexaoBancoDeDados.conexaoMySql;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
public class tabela extends javax.swing.JDialog {

    conexaoMySql iniciaConexaoPesquisa;
    public tabela(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        iniciaConexaoPesquisa = new conexaoMySql();
        jRadioButton1ActionPerformed(null);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setAutoscrolls(false);
        jTable1.setOpaque(false);
        jScrollPane1.setViewportView(jTable1);

        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("Aluno");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("Funcionário");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setText("Visitante");
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton4);
        jRadioButton4.setText("Carro");
        jRadioButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jRadioButton1)
                .addGap(18, 18, 18)
                .addComponent(jRadioButton2)
                .addGap(18, 18, 18)
                .addComponent(jRadioButton3)
                .addGap(18, 18, 18)
                .addComponent(jRadioButton4)
                .addContainerGap(310, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton2)
                    .addComponent(jRadioButton3)
                    .addComponent(jRadioButton4))
                .addGap(16, 16, 16))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 626, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        java.awt.Dimension dialogSize = getSize();
        setLocation((screenSize.width-dialogSize.width)/2,(screenSize.height-dialogSize.height)/2);
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
       // iniciaConexaoPesquisa.fechaConexao();
        iniciaConexaoPesquisa.eventuaCenexao();
        jTable1.updateUI();
        jTable1.getColumnModel().getColumn(0).setPreferredWidth(200);
        jTable1.getColumnModel().getColumn(0).setHeaderValue("Nome");

        jTable1.getColumnModel().getColumn(1).setPreferredWidth(15);
        jTable1.getColumnModel().getColumn(1).setHeaderValue("RG");

        jTable1.getColumnModel().getColumn(2).setPreferredWidth(15);
        jTable1.getColumnModel().getColumn(2).setHeaderValue("Sexo");

         jTable1.getColumnModel().getColumn(3).setPreferredWidth(30);
        jTable1.getColumnModel().getColumn(3).setHeaderValue("Curso");

        DefaultTableModel modelo = (DefaultTableModel)jTable1.getModel();
        modelo.setNumRows(0);
        String comandoTabela = "select alu_nome, alu_rg , alu_sexo, alu_curso from aluno order by alu_nome";

        try
        {

            iniciaConexaoPesquisa.executaComandosSql(comandoTabela);
            while(iniciaConexaoPesquisa.resultset.next())
            {
                modelo.addRow(new Object[]{iniciaConexaoPesquisa.resultset.getString("alu_nome"),
                                           iniciaConexaoPesquisa.resultset.getString("alu_rg"),
                                           iniciaConexaoPesquisa.resultset.getString("alu_sexo"),
                                           iniciaConexaoPesquisa.resultset.getString("alu_curso")});
            }

        }
        catch(SQLException erro)
        {
            JOptionPane.showMessageDialog(this, "Ocurru um erro");
        }
        iniciaConexaoPesquisa.fechaConexao();
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        iniciaConexaoPesquisa.eventuaCenexao();
        jTable1.updateUI();
        jTable1.getColumnModel().getColumn(0).setPreferredWidth(200);
        jTable1.getColumnModel().getColumn(0).setHeaderValue("Nome");

        jTable1.getColumnModel().getColumn(1).setPreferredWidth(15);
        jTable1.getColumnModel().getColumn(1).setHeaderValue("RG");

        jTable1.getColumnModel().getColumn(2).setPreferredWidth(15);
        jTable1.getColumnModel().getColumn(2).setHeaderValue("Sexo");

        jTable1.getColumnModel().getColumn(3).setPreferredWidth(30);
        jTable1.getColumnModel().getColumn(3).setHeaderValue("");

        DefaultTableModel modelo = (DefaultTableModel)jTable1.getModel();
        modelo.setNumRows(0);
        String comandoTabela = "select fun_nome, fun_rg , fun_sexo from funcionario order by fun_nome";

        try
        {

            iniciaConexaoPesquisa.executaComandosSql(comandoTabela);
            while(iniciaConexaoPesquisa.resultset.next())
            {
                modelo.addRow(new Object[]{iniciaConexaoPesquisa.resultset.getString("fun_nome"),
                                           iniciaConexaoPesquisa.resultset.getString("fun_rg"),
                                           iniciaConexaoPesquisa.resultset.getString("fun_sexo")});
            }

        }
        catch(SQLException erro)
        {
            JOptionPane.showMessageDialog(this, "Ocurru um erro");
        }
        iniciaConexaoPesquisa.fechaConexao();
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
         iniciaConexaoPesquisa.eventuaCenexao();
        jTable1.updateUI();
          jTable1.getColumnModel().getColumn(0).setHeaderValue("Nome");
        jTable1.getColumnModel().getColumn(0).setPreferredWidth(200);
       
        jTable1.getColumnModel().getColumn(1).setHeaderValue("RG");
        jTable1.getColumnModel().getColumn(1).setPreferredWidth(15);
        
        jTable1.getColumnModel().getColumn(2).setHeaderValue("Sexo");
        jTable1.getColumnModel().getColumn(2).setPreferredWidth(15);
        
         jTable1.getColumnModel().getColumn(3).setHeaderValue("Data da visita");
         jTable1.getColumnModel().getColumn(3).setPreferredWidth(30);


        

        DefaultTableModel modelo = (DefaultTableModel)jTable1.getModel();
        modelo.setNumRows(0);
        String comandoTabela = "select vis_nome, vis_rg , vis_sexo, vis_data from visitante order by vis_nome";

        try
        {

            iniciaConexaoPesquisa.executaComandosSql(comandoTabela);
            while(iniciaConexaoPesquisa.resultset.next())
            {
                modelo.addRow(new Object[]{iniciaConexaoPesquisa.resultset.getString("vis_nome"),
                                           iniciaConexaoPesquisa.resultset.getString("vis_rg"),
                                           iniciaConexaoPesquisa.resultset.getString("vis_sexo"),
                                           iniciaConexaoPesquisa.resultset.getString("vis_data")});
            }

        }
        catch(SQLException erro)
        {
            JOptionPane.showMessageDialog(this, "Ocurru um erro");
        }
        iniciaConexaoPesquisa.fechaConexao();
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    private void jRadioButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton4ActionPerformed
        iniciaConexaoPesquisa.eventuaCenexao();
        jTable1.updateUI();
          jTable1.getColumnModel().getColumn(0).setHeaderValue("Proprietário");
        jTable1.getColumnModel().getColumn(0).setPreferredWidth(200);

        jTable1.getColumnModel().getColumn(1).setHeaderValue("Placa do veículo");
        jTable1.getColumnModel().getColumn(1).setPreferredWidth(15);

        jTable1.getColumnModel().getColumn(2).setHeaderValue("Tipo do veículo");
        jTable1.getColumnModel().getColumn(2).setPreferredWidth(15);

         jTable1.getColumnModel().getColumn(3).setHeaderValue("Data do cadastro");
         jTable1.getColumnModel().getColumn(3).setPreferredWidth(30);




        DefaultTableModel modelo = (DefaultTableModel)jTable1.getModel();
        modelo.setNumRows(0);
        String comandoTabela = "select vei_proprietario, vei_placa , vei_tipo, vei_data from veiculo order by vei_proprietario";

        try
        {

            iniciaConexaoPesquisa.executaComandosSql(comandoTabela);
            while(iniciaConexaoPesquisa.resultset.next())
            {
                modelo.addRow(new Object[]{iniciaConexaoPesquisa.resultset.getString("vei_proprietario"),
                                           iniciaConexaoPesquisa.resultset.getString("vei_placa"),
                                           iniciaConexaoPesquisa.resultset.getString("vei_tipo"),
                                           iniciaConexaoPesquisa.resultset.getString("vei_data")});
            }

        }
        catch(SQLException erro)
        {
            JOptionPane.showMessageDialog(this, "Ocurru um erro");
        }
        iniciaConexaoPesquisa.fechaConexao();
    }//GEN-LAST:event_jRadioButton4ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                tabela dialog = new tabela(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

}
